apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  resourceRequirement:
    type: ResourceRequirement
    resourceRequirements:
      limits:
        cpu: "1"
        ephemeral-storage: 25Gi
        memory: 1Gi
      requests:
        cpu: "1"
        ephemeral-storage: 25Gi
        memory: 1Gi
  registrationImagePullSpec: quay.io/open-cluster-management/registration:v0.16.0
  workImagePullSpec: quay.io/open-cluster-management/work:v0.16.0
  clusterName: {{ .Name }}
  namespace: open-cluster-management-agent
  externalServerURLs:
    - url: {{ .HubInfo.APIServer }}