kind: Deployment
apiVersion: apps/v1
metadata:
  name: klusterlet
  namespace: open-cluster-management
  labels:
    app: klusterlet
    sigma.ali/app-name: androidcloud
    sigma.ali/instance-group: androidcloudhost
    sigma.ali/site: eu126
    meta.k8s.alipay.com/zone: CZ00C
    sigma.ali/deploy-unit: androidcloud-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klusterlet
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: klusterlet
        sigma.ali/app-name: androidcloud
        sigma.ali/instance-group: androidcloudhost
        sigma.ali/site: eu126
        meta.k8s.alipay.com/zone: CZ00C
        sigma.ali/deploy-unit: androidcloud-dev
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 70
              podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klusterlet
            - weight: 30
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klusterlet
      serviceAccountName: klusterlet
      containers:
        - name: klusterlet
          image: reg.docker.alibaba-inc.com/ant-runtime/registration-operator:v0.5.0
          args:
            - "/registration-operator"
            - "klusterlet"
            - "--enable-sync-labels=true"
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 2
          resources:
            limits:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 25Gi
            requests:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 25Gi